 language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/test_greetings

node_js:  
   - "12"

before_script:
  - psql -c 'create database  test_greetings;' -U postgres
  - psql -U postgres -d test_greetings -a -f table.sql

services:
  - postgresql
  